server:
  port: 8084
spring:
  elasticsearch:
    rest:
      uris: http://192.168.1.15:9020
      username: elastic
      password: 123456
  application:
    name: search-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 20
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 15