server:
  port: 8083
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: thinker
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 25
    lease-expiration-duration-in-seconds: 35
mybatis:
  type-aliases-package: com.leyou.item.pojo