server:
  port: 8083
spring:
  elasticsearch:
    rest:
      uris: http://192.168.1.15:9020
      username: elastic
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5