server:
  port: 8084
spring:
  elasticsearch:
    rest:
      uris: http://192.168.1.7:9200
      username: elastic
      password: 123456
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null  #为了提高响应速度,降低带宽,去掉空的字段
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 20
  instance:
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 15
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000